services:
  db:
    container_name: ncs-db
    environment:
      - POSTGRES_PASSWORD=sapwd
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - shared_network
volumes:
  db:
networks:
  shared_network: